[%General]
BackupDatabase=yes
RequireChallenge=no
AskBeforeClosing=yes
echoMode=2

[Passwords]
GeneratedPasswordLength=3
KillGPGAgent=no
AutoClose=30
PathSeparator= ⟶
DragDropPrompt=yes
WordList=orchard-street-long.txt

[Search]
MaxRecentResults=15
MaxPopularResults=15

[Help]
port=1280
closeserver=yes
