[%General]
BackupDatabase=yes
MaxBackups=0
RequireChallenge=no
AskBeforeClosing=yes
echoMode=2
Debug=false

[Passwords]
GeneratedPasswordLength=3
KillGPGAgent=no
KillGPGAgentOnExit=yes
AutoClose=30
PathSeparator= ⟶
DragDropPrompt=yes
WordList=orchard-street-long.txt

[Search]
MaxRecentResults=15
MaxPopularResults=15

[Categories]
DoubleClickOpen=0

[Help]
port=1280
closeserver=yes
